java -jar Competition\\cserver.jar -d Competition\\competition_levels\ -c "MAClient\\bin\\Release\\MAClient.exe -astar -withorder"
java -jar Competition\\cserver.jar -d Competition\\competition_levels\ -c "MAClient\\bin\\Release\\MAClient.exe -astar -noorder"
java -jar Competition\\cserver.jar -d Competition\\competition_levels\ -c "MAClient\\bin\\Release\\MAClient.exe -greedy -withorder"
java -jar Competition\\cserver.jar -d Competition\\competition_levels\ -c "MAClient\\bin\\Release\\MAClient.exe -greedy -noorder"