java -jar server.jar -l levels/MA2Agent1Box.lvl -c "MAClient\\bin\\Debug\\MAClient.exe" 
java -jar server.jar -l levels/2Agents2Boxes.lvl -c "MAClient\\bin\\Debug\\MAClient.exe" 
java -jar server.jar -l levels/MASimple1.lvl -c "MAClient\\bin\\Debug\\MAClient.exe" 
java -jar server.jar -l levels/collision2.lvl -c "MAClient\\bin\\Debug\\MAClient.exe" 
java -jar server.jar -l levels/collision3.lvl -c "MAClient\\bin\\Debug\\MAClient.exe" 